# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('organiser', models.CharField(max_length=120)),
                ('venue', models.CharField(max_length=120)),
            ],
        ),
    ]
