# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event/'),
        ),
    ]
