# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import ecom.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=ecom.products.models.image_upload_to),
        ),
    ]
